# data parameters
dataset_name: cifar10 # cifar10-mnist-mvtech
# training parameters
num_epochs : 201 # MvTech-Ad:601 Cifar10:201 MNIST:51
batch_size : 64
learning_rate : 1e-3

normal_class : 8 # MvTech: 'capsule'

# target_class = MVTech_good_dict[normal_class]

lamda : 0.5 #MvTech-Ad:0.5 Others:0.01 

img_size : 128


use_bias : False
equal_network_size : False
pretrain : True
direction_loss_only : True

# Test
localization_test : False

experiment_name : 'local_equal_net'
